env:
  screen_size: 84 #size to resize obs to
  grayscale_obs: true #whether to convert obs to grayscale
  stack_size: 4 #number of frames to stack for obs

agent:
  batch_size: 32 #batch size for training
  gamma: 0.99 #discount factor
  epsilon_start: 1.0 #initial epsilon for exploration
  epsilon_end: 0.1 #min epsilon for exploration
  decay_proportion: 0.4 #proportion of training steps over which to decay epsilon
  target_update_freq: 10000 #steps between target network updates
  learning_rate: 0.0001 #lr for optimizer
  buffer_capacity: 1000000 #buffer size for experience replay
  train_buffer: 25000 #steps required before training starts

training:
  steps: 500000 #number of steps to train each agent
  moving_avg_reward_window: 50 #window size for average reward
  success_thresh: 10 #avg reward threshold to consider the agent successful
  num_checkpoints: 10 #number of evaluations to perform during training
  eval_episodes: 20 #number of episodes to run for evaluation

